# https://nitro.unjs.io/deploy/providers/cloudflare.html

name = "playground"
type = "javascript"
account_id = "d4ceb1e65a649b1b1e63a31ec3ff2fcb"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"
